#!/bin/sh
# Run llvm's configure script with customizations necessary for the current
# development host.

scriptname=lli_undef_fix/git/dbin/configure-llvm

case `hostname` in
   dyson)
      PROJ_DIR=/uusoc/scratch/dyson/cas/edu/uut/lli_undef_fix
      host_specific_options='--disable-compiler-version-checks'
      ;;
   *)
      echo error: do not recognize host `hostname`.
      exit -1
      ;;
esac

# TODO2: consider running `gcc --version`, and if version is 4.6, then
# setting --disable-compiler-version-checks. 


cd $PROJ_DIR/git/llvm
exec $PROJ_DIR/git/llvm/configure --prefix $PROJ_DIR/live \
      $host_specific_options "$@"

# end of script

