#!/bin/bash
# build llvm and install it


BUILD_ROOT=/uusoc/scratch/dyson/cas/edu/uut/lli_undef_fix/git/llvm
# TODO: change to use PROJ_ROOT to compute the BUILD_ROOT directory.  This
# may mean that the setup script needs to set the PROJ_ROOT environment
# variable.

cd $BUILD_ROOT
echo pwd=`pwd` #;;

start_time=`date +%s`
make -j 3 "$@"
make_status=$?

if [ $make_status -eq 0 ]; then
   echo " "
   echo ====================================================================
   make install
   make_status=$?
fi

# compute build time
stop_time=`date +%s`

elapsed_s=$(( $stop_time - $start_time ))
elapsed_min=$(( $elapsed_s / 60 ))
elapsed_min_rem_s=$(( $elapsed_s % 60 ))

echo build status=$make_status \(should be 0\)
printf "build time %d:%2.2d (%d s)\n" \
      $elapsed_min $elapsed_min_rem_s $elapsed_s 

# ---------------------------------------------------------------------------
# end of script

