#!/bin/bash
# build llvm and install it


BUILT_ROOT=/uusoc/scratch/dyson/cas/edu/uut/lli_undef_fix/git/llvm
# TODO: change to use PROJ_ROOT to compute the BUILD_ROOT directory.  This
# may mean that the setup script needs to set the PROJ_ROOT environment
# variable.

cd $BUILD_ROOT
make "$@"
make install

# ---------------------------------------------------------------------------
# end of script

